---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: todo
  name: todo
spec:
  containers:
    -
      image: "ktothep/version3"
      name: todo
      ports:
        -
          containerPort: 5000
    -
      image: mongo
      name: mongo
      ports:
        -
          containerPort: 27017
